name: github actions example

on:
  workflow_dispatch

jobs:
  main:
    name    : confirm context
    runs-on : ubuntu-latest
    steps   :
      - name  : Checkout repository
        run   : echo "$GITHUB_CONTEXT"
