name: github actions example

on:
  workflow_dispatch

jobs:
  main:
    name    : echo context
    runs-on : ubuntu-latest
    steps   :
      - name  : Checkout repository
        env   :
          GITHUB_CONTEXT : ${{ toJson(github) }}
        run   : |
          echo "$GITHUB_CONTEXT"
