name: github actions example

on:
  workflow_dispatch

jobs:
  name: confirm context
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run : echo "$GITHUB_CONTEXT"
