name: "[release] image : official"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  REGISTRY   : ghcr.io

jobs:
  build-and-push-image:
    name    : Build => Push to ghcr.io
    # if 文で正規表現 ( 'images/*/releases/*-rc' ) が使えない為、やや緩めの判定で妥協。
    if      : |
      github.event.pull_request.merged == true && 
      startsWith(github.event.pull_request.head.ref, 'images/') &&
      contains(github.event.pull_request.head.ref, '/releases/') &&
      endsWith(github.event.pull_request.head.ref, '-rc')
    runs-on : ubuntu-latest
    steps   :
      - name  : env
        env   :
          GITHUB_CONTEXT : ${{ toJson(github) }}
          MERGED_BRANCH  : ${{ github.event.pull_request.head.ref }}
        run   : |
          echo "GITHUB_CONTEXT : $GITHUB_CONTEXT"

          branch="${MERGED_BRANCH}"
          echo "branch : $branch"

          image="$(cut -d '/' -f 2 <<< $branch)"
          echo "image : $image"
          
          version_rc="${branch/images\/$image\/releases\//}"
          version="${version_rc%-*}"
          echo "version_rc : $version_rc"
          echo "version    : $version"

          # 注 : push 時と格納変数名が違うので wrap
          repo_owner="${repository_owner}"
          repo_name="${repository/$repo_owner\//}"

          echo "IMAGE_NAME=$image" >> $GITHUB_ENV
          echo "IMAGE_TAG=$version" >> $GITHUB_ENV
          echo "REPO_OWNER_LOWERCASE=${repo_owner,,}" >> ${GITHUB_ENV}
          echo "REPO_NAME_LOWERCASE=${repo_name,,}" >> ${GITHUB_ENV}    

      - name  : Checkout repository
        uses  : actions/checkout@v2

      - name  : Log in to the Container registry
        uses  : docker/login-action@v1
        with  :
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name  : Build and push Docker image
        uses  : docker/build-push-action@v2
        with  :
          context : ./images/${{ env.IMAGE_NAME }}
          # file    : Dockerfile
          push    : true
          tags    : ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWERCASE }}/${{ env.REPO_NAME_LOWERCASE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name  : Create Release
        uses  : actions/create-release@v1
        env   :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with  :
          tag_name     :         ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWERCASE }}/${{ env.REPO_NAME_LOWERCASE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          release_name : release ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWERCASE }}/${{ env.REPO_NAME_LOWERCASE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          body         : |
            ## CHANGELOG
            - commits url : ${{ github.event.pull_request.commits_url }}
          draft        : false
          prerelease   : false


#on:
#  release:
#    types:
#      - published
#
#jobs:
#   build-and-push-image:
#     name    : Build => Push to ghcr.io
#     runs-on : ubuntu-latest
#     steps   :

