name: "[release] image : rc"

on:
  push:
    branches:
      - 'images/*/releases/*-rc'   # - 'images/*/releases/*-rc*' # rc 以下は workflow 内で生成する。

env:
  REGISTRY   : ghcr.io

jobs:
  build-and-push-image:
    name    : Build => Push to ghcr.io
    runs-on : ubuntu-latest
    steps   :
      - name  : env
        env   :
          GITHUB_CONTEXT : ${{ toJson(github) }}
          GITHUB_REF     : ${{ github.ref }}
          REPO_OWNER     : ${{ github.repository_owner }}
          REPO_NAME      : ${{ github.event.repository.name }}
        run   : |
          echo "GITHUB_CONTEXT : $GITHUB_CONTEXT"

          branch="${GITHUB_REF/refs\/heads\//}"
          echo "branch : $$branch"

          image="$(cut -d '/' -f 2 <<< $branch)"
          echo "image : $image"
          
          version="${branch/images\/$image\/releases\//}"
          echo "version : $version"
          
          datetime=$(TZ=UTC-9 date +'%Y-%m-%d.%H-%M-%S')
          echo "datetime : $datetime"

          echo "IMAGE_NAME=$image" >> $GITHUB_ENV
          echo "IMAGE_TAG=$version.$datetime" >> $GITHUB_ENV
          echo "REPO_OWNER_LOWERCASE=${REPO_OWNER,,}" >> ${GITHUB_ENV}
          echo "REPO_NAME_LOWERCASE=${REPO_NAME,,}" >> ${GITHUB_ENV}

      - name  : Checkout repository
        uses  : actions/checkout@v2

      - name  : Log in to the Container registry
        uses  : docker/login-action@v1
        with  :
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name  : Build and push Docker image
        uses  : docker/build-push-action@v2
        with  :
          context : ./images/${{ env.IMAGE_NAME }}
          # file    : Dockerfile
          push    : true
          tags    : ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWERCASE }}/${{ env.REPO_NAME_LOWERCASE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name  : Tag branch
        run   : |
          git tag         ${{ env.IMAGE_NAME }}@${{ env.IMAGE_TAG }}
          git push origin ${{ env.IMAGE_NAME }}@${{ env.IMAGE_TAG }}
